name: translations_cleaner
description: Package to remove unused keys in arb files, across all translations
version: 0.1.0
repository: https://github.com/Chinmay-KB/translations_cleaner

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.3.1
  glob: ^2.1.0
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
